name: CI Pipeline avec Trivy

on:
  push:
    branches:
      - main
      - trivy
  pull_request:

jobs:
  build:
    name: Build du projet
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Simulation du build
        run: echo "Build réussi"

  scan-trivy:
    name: Scan de sécurité avec Trivy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Analyse des vulnérabilités
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: scan-trivy

    steps:
      - name: Déploiement simulé
        run: echo "Déploiement effectué avec succès"